overwrite: true
schema: 'http://localhost:3100/graphql'
documents: './src/graphql/operations/*.graphql'
generates:
  src/graphql/generated.tsx:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'    
    config:
      declarationKind: 'interface'
      withHooks: true
      withRefetchFn: true
      dedupeOperationSuffix: true
      useTypeImports: true
      scalars:
        DateTime: Date

